spring:
  application:
    name: tinterest
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  mail:
    host: smtp.mail.ru
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8443
  ssl:
    enabled: true
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tinterest

app:
  jwt:
    access-token-expiration-ms: 900000
    refresh-token-expiration-days: 15