spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tinterest_db

server:
  ssl:
    key-store: classpath:keystore.p12

app:
  jwt:
    private-key: classpath:keys/private.pem
    public-key: classpath:keys/public.pem