spring:
  application:
    name: tinterest
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:tinterest_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: ${MAIL_HOST:smtp.mail.ru}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

server:
  port: ${SERVER_PORT:8443}
  ssl:
    enabled: ${SSL_ENABLED:true}
    key-store: ${SSL_KEYSTORE_PATH:file:./secrets/keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:123456}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:tinterest}

app:
  mail:
    enabled: ${MAIL_ENABLED:false}
  jwt:
    private-key: ${JWT_PRIVATE_KEY_PATH:file:./secrets/keys/private.pem}
    public-key: ${JWT_PUBLIC_KEY_PATH:file:./secrets/keys/public.pem}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}
    refresh-token-expiration-days: ${JWT_REFRESH_TOKEN_EXPIRATION_DAYS:15}
  minio:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    public-endpoint: ${MINIO_PUBLIC_ENDPOINT:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minioadmin}
    secret-key: ${MINIO_SECRET_KEY:minioadmin}
    bucket: ${MINIO_BUCKET:tinterest-images}
