package com.luxus.tinterest.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    UNAUTHORIZED,
    FORBIDDEN,
    INVALID_CODE,
    MANY_ATTEMPTS,
    CODE_EXPIRED,
    EMAIL_ALREADY_CONFIRMED,
    INVALID_CREDENTIALS,
    USER_BLOCKED,
    EMAIL_NOT_VERIFIED,
    INVALID_INTERESTS,
    INVALID_REFRESH_TOKEN,
    REFRESH_TOKEN_REUSE_DETECTED,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_REVOKED,
    CHAT_NOT_FOUND,
    CHAT_ACCESS_DENIED,
    INVALID_CHAT_OPERATION,
    INVALID_AVATAR_FILE,
    STORAGE_ERROR
}
