name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Run Maven tests
        run: mvn test

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

  reports:
    if: always()  # Джоба будет выполнена вне зависимости от успеха или неуспеха run-tests
    needs: [ run-tests ]  # Выполняется после успешного (или завершённого) run-tests
    runs-on: ubuntu-latest  # Тоже запускается в Ubuntu

    steps:
      - name: Check out repository
        uses: actions/checkout@v4  # Клонируем репозиторий
        with:
          ref: gh-pages  # Клонируем ветку gh-pages
          path: gh-pages  # Указываем путь, куда клонировать

      - name: Download Allure results
        uses: actions/download-artifact@v4  # Загружаем ранее загруженные результаты
        with:
          name: allure-results  # Имя артефакта
          path: allure-results  # Путь куда распаковать

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.12  # Генерируем Allure-отчёт
        if: always()  # Выполняем даже при ошибке
        with:
          allure_results: allure-results  # Путь к результатам
          allure_history: allure-history  # Папка с историей отчётов (для графиков и сравнения)

      - name: Deploy report to Github Pages
        if: always()  # Выполняем даже если предыдущие шаги упали
        uses: peaceiris/actions-gh-pages@v4  # Деплой на GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Используем встроенный GitHub токен
          publish_branch: gh-pages  # Ветка для публикации отчёта
          publish_dir: allure-history  # Папка с готовым HTML отчётом
